CREATE TABLE IF NOT EXISTS blogs(
  id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  body MEDIUMTEXT,
  imgUrl VARCHAR(255),
  title VARCHAR(255),
  published TINYINT
) DEFAULT charset utf8;
CREATE TABLE IF NOT EXISTS comments(
  id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  body MEDIUMTEXT,
  blogId int NOT NULL,
  FOREIGN KEY (blogId) REFERENCES blogs(id) ON DELETE CASCADE
) DEFAULT charset utf8;